apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ejie-corp
  description: The demo-corp organization
  links:
    - url: http://www.backstage.io/
      title: Website
spec:
  type: organization
  profile:
    displayName: Ejie Corp
    email: ejie-corp@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [it-ejie]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-group
  description: A Backstage example group
spec:
  targets:
    - ./it-dept.yaml
    - ./cloudops-dept.yaml
    
    
