apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-integracion
  description: service-integracion
  tags:
    - javascript
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=yelb-ui,tier=frontend'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://app01-ui.example.com
      title: 'App01 Information'
      icon: locallibrary
spec:
  type: service
  lifecycle: experimental
  owner: cloudops
  system: d006-mensajeshlt7
  
